import type { Invoice } from "./types";

const day = (offset: number) => {
  const d = new Date(2026, 8, 18);
  d.setDate(d.getDate() + offset);
  return d.toISOString().slice(0, 10);
};

export function sampleInvoices(): Invoice[] {
  return [
    {
      id: "inv-northwind",
      vendor: "Northwind Cloud Systems",
      invoiceNumber: "NW-20481",
      issueDate: day(-9),
      dueDate: day(21),
      currency: "USD",
      subtotal: 18400,
      tax: 1564,
      total: 19964,
      status: "review",
      poId: "po-northwind-1",
      glAccount: "6010 · Software & SaaS",
      department: "Engineering",
      memo: "Annual platform renewal",
      tags: [],
      lineItems: [
        {
          id: "li-1",
          description: "Compute cluster — annual commitment",
          quantity: 1,
          unitPrice: 14200,
          amount: 14200,
          glAccount: "6010 · Software & SaaS",
          department: "Engineering",
        },
        {
          id: "li-2",
          description: "Observability add-on (12 mo)",
          quantity: 12,
          unitPrice: 350,
          amount: 4200,
          glAccount: "6010 · Software & SaaS",
          department: "Engineering",
        },
      ],
      provenance: {
        vendor: "read",
        invoiceNumber: "read",
        issueDate: "read",
        dueDate: "read",
        subtotal: "read",
        tax: "read",
        total: "read",
      },
      audit: [
        {
          id: "a1",
          at: day(-9) + "T09:12:00Z",
          actor: "OCR engine",
          action: "Document ingested and parsed",
        },
        {
          id: "a2",
          at: day(-9) + "T09:14:00Z",
          actor: "Luuk Koppen",
          action: "Submitted for approval",
        },
      ],
      source: "sample",
      createdAt: day(-9),
    },
    {
      id: "inv-atlas",
      vendor: "Atlas Print & Signage",
      invoiceNumber: "AP-7741",
      issueDate: day(-4),
      dueDate: day(11),
      currency: "USD",
      subtotal: 3250,
      tax: 276.25,
      total: 3526.25,
      status: "draft",
      glAccount: "6030 · Marketing",
      department: "Marketing",
      memo: "Q4 conference booth",
      tags: [],
      lineItems: [
        {
          id: "li-1",
          description: "Booth backdrop panels",
          quantity: 5,
          unitPrice: 410,
          amount: 2050,
          glAccount: "6030 · Marketing",
          department: "Marketing",
        },
        {
          id: "li-2",
          description: "Brochures (2,000 units)",
          quantity: 2000,
          unitPrice: 0.6,
          amount: 1200,
          glAccount: "6030 · Marketing",
          department: "Marketing",
        },
      ],
      provenance: {
        vendor: "read",
        invoiceNumber: "read",
        issueDate: "read",
        dueDate: "read",
        subtotal: "read",
        tax: "read",
        total: "read",
      },
      audit: [
        {
          id: "a1",
          at: day(-4) + "T15:02:00Z",
          actor: "OCR engine",
          action: "Document ingested and parsed",
        },
      ],
      source: "sample",
      createdAt: day(-4),
    },
    {
      id: "inv-helix",
      vendor: "Helix Legal LLP",
      invoiceNumber: "HLX-1188",
      issueDate: day(-18),
      dueDate: day(2),
      currency: "USD",
      subtotal: 9600,
      tax: 0,
      total: 9600,
      status: "scheduled",
      glAccount: "6020 · Professional services",
      department: "Finance",
      memo: "Vendor contract review",
      tags: ["First-time vendor"],
      lineItems: [
        {
          id: "li-1",
          description: "Senior counsel — 24 hrs",
          quantity: 24,
          unitPrice: 400,
          amount: 9600,
          glAccount: "6020 · Professional services",
          department: "Finance",
        },
      ],
      provenance: {
        vendor: "read",
        invoiceNumber: "read",
        issueDate: "read",
        dueDate: "read",
        subtotal: "read",
        tax: "read",
        total: "read",
      },
      audit: [
        {
          id: "a1",
          at: day(-18) + "T11:00:00Z",
          actor: "OCR engine",
          action: "Document ingested and parsed",
        },
        {
          id: "a2",
          at: day(-17) + "T08:30:00Z",
          actor: "Luuk Koppen",
          action: "Submitted for approval",
        },
        {
          id: "a3",
          at: day(-16) + "T16:45:00Z",
          actor: "Dana Whitfield",
          action: "Approved",
          note: "Within contracted rate card",
        },
      ],
      source: "sample",
      createdAt: day(-18),
    },
    {
      id: "inv-vertex",
      vendor: "Vertex Facilities Group",
      invoiceNumber: "VF-3025",
      issueDate: day(-25),
      dueDate: day(-1),
      currency: "USD",
      subtotal: 7450,
      tax: 633.25,
      total: 8083.25,
      status: "scheduled",
      glAccount: "6050 · Office & facilities",
      department: "Operations",
      memo: "September facilities retainer",
      tags: ["Recurring"],
      lineItems: [
        {
          id: "li-1",
          description: "Facilities management retainer",
          quantity: 1,
          unitPrice: 6200,
          amount: 6200,
          glAccount: "6050 · Office & facilities",
          department: "Operations",
        },
        {
          id: "li-2",
          description: "HVAC quarterly service",
          quantity: 1,
          unitPrice: 1250,
          amount: 1250,
          glAccount: "6050 · Office & facilities",
          department: "Operations",
        },
      ],
      provenance: {
        vendor: "read",
        invoiceNumber: "read",
        issueDate: "read",
        dueDate: "read",
        subtotal: "read",
        tax: "read",
        total: "read",
      },
      audit: [
        {
          id: "a1",
          at: day(-25) + "T10:05:00Z",
          actor: "OCR engine",
          action: "Document ingested and parsed",
        },
        {
          id: "a2",
          at: day(-24) + "T09:20:00Z",
          actor: "Luuk Koppen",
          action: "Submitted for approval",
        },
        { id: "a3", at: day(-23) + "T13:10:00Z", actor: "Dana Whitfield", action: "Approved" },
        {
          id: "a4",
          at: day(-22) + "T09:00:00Z",
          actor: "Luuk Koppen",
          action: "Marked ready for external handoff",
        },
      ],
      source: "sample",
      createdAt: day(-25),
    },
  ];
}

export function sampleHistory(): Invoice[] {
  return [
    {
      id: "inv-lumen",
      vendor: "Lumen Hardware Supply",
      invoiceNumber: "LHS-88420",
      issueDate: day(-40),
      dueDate: day(-12),
      currency: "USD",
      subtotal: 12980,
      tax: 1103.3,
      total: 14083.3,
      status: "paid",
      glAccount: "6060 · Hardware & equipment",
      department: "Operations",
      memo: "Laptop refresh batch 3",
      tags: ["High value", "Urgent"],
      lineItems: [
        {
          id: "li-1",
          description: 'Laptops 14" (10 units)',
          quantity: 10,
          unitPrice: 1180,
          amount: 11800,
          glAccount: "6060 · Hardware & equipment",
          department: "Operations",
        },
        {
          id: "li-2",
          description: "Docking stations",
          quantity: 10,
          unitPrice: 118,
          amount: 1180,
          glAccount: "6060 · Hardware & equipment",
          department: "Operations",
        },
      ],
      provenance: {
        vendor: "read",
        invoiceNumber: "read",
        issueDate: "read",
        dueDate: "read",
        subtotal: "read",
        tax: "read",
        total: "read",
      },
      audit: [
        {
          id: "a1",
          at: day(-40) + "T08:00:00Z",
          actor: "OCR engine",
          action: "Document ingested and parsed",
        },
        {
          id: "a2",
          at: day(-39) + "T09:00:00Z",
          actor: "Luuk Koppen",
          action: "Submitted for approval",
        },
        { id: "a3", at: day(-38) + "T10:00:00Z", actor: "Dana Whitfield", action: "Approved" },
        {
          id: "a4",
          at: day(-37) + "T10:30:00Z",
          actor: "Luuk Koppen",
          action: "Marked ready for external handoff",
        },
        {
          id: "a5",
          at: day(-30) + "T12:00:00Z",
          actor: "Payments",
          action: "Historical completion recorded (sample data)",
          note: "Imported demo history; no payment was sent by Foundry.",
        },
      ],
      source: "sample",
      createdAt: day(-40),
    },
  ];
}
