/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exceptions': typeof ExceptionsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/vendors': typeof VendorsRoute
  '/invoices/$id': typeof InvoicesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exceptions': typeof ExceptionsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/vendors': typeof VendorsRoute
  '/invoices/$id': typeof InvoicesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exceptions': typeof ExceptionsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/vendors': typeof VendorsRoute
  '/invoices/$id': typeof InvoicesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exceptions'
    | '/history'
    | '/settings'
    | '/vendors'
    | '/invoices/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exceptions'
    | '/history'
    | '/settings'
    | '/vendors'
    | '/invoices/$id'
  id:
    | '__root__'
    | '/'
    | '/exceptions'
    | '/history'
    | '/settings'
    | '/vendors'
    | '/invoices/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExceptionsRoute: typeof ExceptionsRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  VendorsRoute: typeof VendorsRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExceptionsRoute: ExceptionsRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  VendorsRoute: VendorsRoute,
  InvoicesIdRoute: InvoicesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
